---
title: "Data_discription"
output: html_document
---

# Data Source

In this project, we use data of Youth Risk Behavior Surveillance System (YRBSS) collected by Centers for Disease Control and Prevention (CDC). YRBSS was established in 1990 to monitor health behaviors among U.S. adolescents and adults that are leading causes of death, disability, and social problems. Information about YRBSS can be found at [*Youth Risk Behavior Surveillance System (YRBSS) Overview*](https://www.cdc.gov/healthyyouth/data/yrbs/overview.htm). Among six categories of health-related behaviors that YRBSS monitors, we mainly focus on drug use abuse among youth. The YRBSS data are collected every two years, and the most up-to-date data were collected in 2019. We will use the data collected in 2019 on the state level.

The dataset is so large that it exceeds the upload limit of github. Therefore, in order to download the dataset, you can use the code in `download_dataset.Rmd` (https://github.com/ryan2417/drug_abuse_among_youth.github.io/blob/main/download_dataset.Rmd).



# Data Cleaning 
```{r}
#yrbss_state
```

# Variable desciribe

