---
title: "Data tidy"
output: github_document
---

```{r}
library(tidyverse)
library(survey)
library(viridis)
library(table1)
library(kableExtra)

knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  echo = FALSE
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d(option = "viridis")
scale_fill_discrete = scale_fill_viridis_d(option = "viridis")
```


```{r}
drug_use_tidy <- function(input_list){
  output <- case_when(input_list == 1 ~ 0,
                      input_list == 2 ~ 1.5,
                      input_list == 3 ~ 6,
                      input_list == 4 ~ 14.5,
                      input_list == 5 ~ 29.5,
                      input_list > 5 ~ 40)
  return(output)
}
drug_use_frequency <- function(input_list){
  output <- case_when(input_list == 0 ~ "No Drug Use",
                      input_list > 0 & input_list < 40 ~ "Light Dose",
                      input_list >= 40 ~ "Heavy Dose")
}

age_tidy <- function(input_list) {
  output <- case_when(input_list == 1 ~ NA_real_,
                      input_list == 2 ~ 8,
                      input_list == 3 ~ 9.5,
                      input_list == 4 ~ 11.5,
                      input_list == 5 ~ 13.5,
                      input_list == 6 ~ 15.5,
                      input_list == 7 ~ 17.5)
}

firstage_tidy <- function(input_list){
  output <- case_when(input_list == 1 ~ "never",
                      input_list == 2 ~ "8 years old or younger",
                      input_list == 3 ~ "9 or 10 years old",
                      input_list == 4 ~ "11 or 12 years old",
                      input_list == 5 ~ "13 or 14 years old",
                      input_list == 6 ~ "15 or 16 years old",
                      input_list == 7 ~ "17 years old or older")
  return(output)
}
```


```{r import data}
yrbss_state_a <- readRDS("data/2019 states a-m.rds")
yrbss_state_z <- readRDS("data/2019 states n-z.rds")
yrbss_state = rbind(yrbss_state_a,yrbss_state_z)
yrbss_state = as_tibble(yrbss_state)
```


```{r export csv}
yrbss_state_tidy_additional <-
  yrbss_state %>% 
  drop_na(q31, q40, q45, q46, q50, q51, q52, q53, q54, q55, q56, q9, q10, q14, q17, q26, q39,q59, q79, q80, q88, q33, q42, q89, q8, q11, grade, race4, sex) %>% 
  mutate(
    grade = fct_recode(factor(grade, ordered = TRUE), 
                       "9th Grade" = "1",
                       "10th Grade" = "2",
                       "11th Grade" = "3",
                       "12th Grade" = "4"),
    sex = fct_recode(factor(sex, ordered = TRUE), 
                       "female" = "1",
                       "male" = "2"),
    race4 = fct_recode(factor(race4), 
                       "White" = "1",
                       "Black or African American" = "2",
                       "Hispanic/Latino" = "3",
                       "All other Races" = "4"),
    age_initial_alcohol = age_tidy(q40),
    age_initial_smoking = age_tidy(q31),
    age_marijuana = age_tidy(q46),
    marijuana = drug_use_tidy(q45),
    cocaine = drug_use_tidy(q50),
    inhale = drug_use_tidy(q51),
    heroin = drug_use_tidy(q52),
    methamphetamine = drug_use_tidy(q53),
    ecstasy = drug_use_tidy(q54),
    steroid = drug_use_tidy(q55),
    illegal_injection = case_when(q56 == 1 ~ 0,
                                  q56 == 2 ~ 20,
                                  q56 == 3 ~ 40),
    drug_use_sum = rowSums(across(marijuana:illegal_injection)),
    other_drug_sum = rowSums(across(cocaine:illegal_injection)),
    drug_use_freq = drug_use_frequency(drug_use_sum),
    drunk_driving = ifelse(q9 > 1 | q10 > 2, "Yes", "No"),
    text_driving = ifelse(q11 == 2, "No", "Yes"),
    carrying_weapon = ifelse(q14 == 1, "No", "Yes"),
    suicide_attempt = ifelse(q26 == 1, "Yes", "No"),
    quit_smoke = case_when(q39 == 1 ~ "Never Smoke",
                           q39 == 2 ~ "Yes",
                           q39 == 3 ~ "No"),
    physical_fight = ifelse(q17 == 1, "No", "Yes"),
    early_sex = ifelse(q59 > 1 & q59 <= 5 , "Yes", "No"),
    q79 = as.numeric(q79),
    q80 = as.numeric(q80),
    tv_use = case_when(q79 == 1 ~ 0, 
                       q79 == 2 ~ 0.5,
                       q79 > 2 ~ q79 - 2),
    computer_use = q80 - 2,
    computer_use = case_when(q80 == 1 ~ 0, 
                       q80 == 2 ~ 0.5,
                       q80 > 2 ~ q80 - 2),
    screening_use = tv_use + computer_use,
    heavy_screen_use = ifelse(screening_use >= 5, "Yes", "No"),
    sleeping_time = as.numeric(q88) + 3,
    enough_sleep = ifelse(sleeping_time >= 8, "Yes", "No"),
    smoking_status = case_when(q33 == 1 ~ "Never Smoker",
                               q33 >= 2 & q33 <= 5 ~ "Light Smoker",
                               q33 >=6 ~ "Heavy Smoker"),
    binge_drinking = case_when(q42 == 1 ~ "No Binge Drinking",
                               q42 >= 2 & q42 <= 4 ~ "Light Binge Drinking",
                               q42 >=5 ~ "Heavy Binge Drinking"),
    seat_belt = case_when(q8 <= 2 ~ "Never or Rarely",
                          q8 == 3 ~ "Sometimes",
                          q8 >= 4 ~ "Most of the time or Always"),
    grades_school = case_when(q89 == 1 ~ "Mostly A's",
                       q89 == 2 ~ "Mostly B's",
                       q89 == 3 ~ "Mostly C's",
                       q89 %in% c(4,5) ~ "Mostly Below C's",
                       q89 == 6 ~ "None of these grades",
                       q89 == 7 ~ "Not sure"),
    grades_school = factor(grades_school, level = c("Mostly A's", "Mostly B's", "Mostly C's", "Mostly Below C's", "None of these grades", "Not sure")),
    smoke_age = firstage_tidy(q31),
    alcohol_age = firstage_tidy(q40)
    ) %>% 
  select(drug_use_freq, grade, sex, bmi, race4, drunk_driving, text_driving, carrying_weapon, suicide_attempt, quit_smoke, physical_fight, early_sex, screening_use, heavy_screen_use, sleeping_time, enough_sleep, smoking_status, binge_drinking, seat_belt, grades_school, smoke_age, alcohol_age, age_initial_alcohol, age_initial_smoking) %>% 
  write_csv(file = "data/yrbss_state_tidy_additional.csv")


```
